import { h, SDOM } from './';
import { Props } from './props';

declare module "./index" {
  export interface H<Model, Action> {
    a: NamedH<Model, Action, HTMLElementTagNameMap['a']>;
    abbr: NamedH<Model, Action, HTMLElementTagNameMap['abbr']>;
    address: NamedH<Model, Action, HTMLElementTagNameMap['address']>;
    applet: NamedH<Model, Action, HTMLElementTagNameMap['applet']>;
    area: NamedH<Model, Action, HTMLElementTagNameMap['area']>;
    article: NamedH<Model, Action, HTMLElementTagNameMap['article']>;
    aside: NamedH<Model, Action, HTMLElementTagNameMap['aside']>;
    audio: NamedH<Model, Action, HTMLElementTagNameMap['audio']>;
    b: NamedH<Model, Action, HTMLElementTagNameMap['b']>;
    base: NamedH<Model, Action, HTMLElementTagNameMap['base']>;
    basefont: NamedH<Model, Action, HTMLElementTagNameMap['basefont']>;
    bdo: NamedH<Model, Action, HTMLElementTagNameMap['bdo']>;
    blockquote: NamedH<Model, Action, HTMLElementTagNameMap['blockquote']>;
    body: NamedH<Model, Action, HTMLElementTagNameMap['body']>;
    br: NamedH<Model, Action, HTMLElementTagNameMap['br']>;
    button: NamedH<Model, Action, HTMLElementTagNameMap['button']>;
    canvas: NamedH<Model, Action, HTMLElementTagNameMap['canvas']>;
    caption: NamedH<Model, Action, HTMLElementTagNameMap['caption']>;
    cite: NamedH<Model, Action, HTMLElementTagNameMap['cite']>;
    code: NamedH<Model, Action, HTMLElementTagNameMap['code']>;
    col: NamedH<Model, Action, HTMLElementTagNameMap['col']>;
    colgroup: NamedH<Model, Action, HTMLElementTagNameMap['colgroup']>;
    data: NamedH<Model, Action, HTMLElementTagNameMap['data']>;
    datalist: NamedH<Model, Action, HTMLElementTagNameMap['datalist']>;
    dd: NamedH<Model, Action, HTMLElementTagNameMap['dd']>;
    del: NamedH<Model, Action, HTMLElementTagNameMap['del']>;
    details: NamedH<Model, Action, HTMLElementTagNameMap['details']>;
    dfn: NamedH<Model, Action, HTMLElementTagNameMap['dfn']>;
    dialog: NamedH<Model, Action, HTMLElementTagNameMap['dialog']>;
    dir: NamedH<Model, Action, HTMLElementTagNameMap['dir']>;
    div: NamedH<Model, Action, HTMLElementTagNameMap['div']>;
    dl: NamedH<Model, Action, HTMLElementTagNameMap['dl']>;
    dt: NamedH<Model, Action, HTMLElementTagNameMap['dt']>;
    em: NamedH<Model, Action, HTMLElementTagNameMap['em']>;
    embed: NamedH<Model, Action, HTMLElementTagNameMap['embed']>;
    fieldset: NamedH<Model, Action, HTMLElementTagNameMap['fieldset']>;
    figcaption: NamedH<Model, Action, HTMLElementTagNameMap['figcaption']>;
    figure: NamedH<Model, Action, HTMLElementTagNameMap['figure']>;
    font: NamedH<Model, Action, HTMLElementTagNameMap['font']>;
    footer: NamedH<Model, Action, HTMLElementTagNameMap['footer']>;
    form: NamedH<Model, Action, HTMLElementTagNameMap['form']>;
    frame: NamedH<Model, Action, HTMLElementTagNameMap['frame']>;
    frameset: NamedH<Model, Action, HTMLElementTagNameMap['frameset']>;
    h1: NamedH<Model, Action, HTMLElementTagNameMap['h1']>;
    h2: NamedH<Model, Action, HTMLElementTagNameMap['h2']>;
    h3: NamedH<Model, Action, HTMLElementTagNameMap['h3']>;
    h4: NamedH<Model, Action, HTMLElementTagNameMap['h4']>;
    h5: NamedH<Model, Action, HTMLElementTagNameMap['h5']>;
    h6: NamedH<Model, Action, HTMLElementTagNameMap['h6']>;
    head: NamedH<Model, Action, HTMLElementTagNameMap['head']>;
    header: NamedH<Model, Action, HTMLElementTagNameMap['header']>;
    hgroup: NamedH<Model, Action, HTMLElementTagNameMap['hgroup']>;
    hr: NamedH<Model, Action, HTMLElementTagNameMap['hr']>;
    html: NamedH<Model, Action, HTMLElementTagNameMap['html']>;
    i: NamedH<Model, Action, HTMLElementTagNameMap['i']>;
    iframe: NamedH<Model, Action, HTMLElementTagNameMap['iframe']>;
    img: NamedH1<Model, Action, HTMLElementTagNameMap['img']>;
    input: NamedH1<Model, Action, HTMLElementTagNameMap['input']>;
    ins: NamedH<Model, Action, HTMLElementTagNameMap['ins']>;
    kbd: NamedH<Model, Action, HTMLElementTagNameMap['kbd']>;
    label: NamedH<Model, Action, HTMLElementTagNameMap['label']>;
    legend: NamedH<Model, Action, HTMLElementTagNameMap['legend']>;
    li: NamedH<Model, Action, HTMLElementTagNameMap['li']>;
    link: NamedH<Model, Action, HTMLElementTagNameMap['link']>;
    main: NamedH<Model, Action, HTMLElement>;
    map: NamedH<Model, Action, HTMLElementTagNameMap['map']>;
    mark: NamedH<Model, Action, HTMLElementTagNameMap['mark']>;
    marquee: NamedH<Model, Action, HTMLElementTagNameMap['marquee']>;
    menu: NamedH<Model, Action, HTMLElementTagNameMap['menu']>;
    meta: NamedH<Model, Action, HTMLElementTagNameMap['meta']>;
    meter: NamedH<Model, Action, HTMLElementTagNameMap['meter']>;
    nav: NamedH<Model, Action, HTMLElementTagNameMap['nav']>;
    noscript: NamedH<Model, Action, HTMLElementTagNameMap['noscript']>;
    object: NamedH<Model, Action, HTMLElementTagNameMap['object']>;
    ol: NamedH<Model, Action, HTMLElementTagNameMap['ol']>;
    optgroup: NamedH<Model, Action, HTMLElementTagNameMap['optgroup']>;
    option: NamedH<Model, Action, HTMLElementTagNameMap['option']>;
    output: NamedH<Model, Action, HTMLElementTagNameMap['output']>;
    p: NamedH<Model, Action, HTMLElementTagNameMap['p']>;
    param: NamedH<Model, Action, HTMLElementTagNameMap['param']>;
    picture: NamedH<Model, Action, HTMLElementTagNameMap['picture']>;
    pre: NamedH<Model, Action, HTMLElementTagNameMap['pre']>;
    progress: NamedH<Model, Action, HTMLElementTagNameMap['progress']>;
    q: NamedH<Model, Action, HTMLElementTagNameMap['q']>;
    rt: NamedH<Model, Action, HTMLElementTagNameMap['rt']>;
    ruby: NamedH<Model, Action, HTMLElementTagNameMap['ruby']>;
    s: NamedH<Model, Action, HTMLElementTagNameMap['s']>;
    samp: NamedH<Model, Action, HTMLElementTagNameMap['samp']>;
    script: NamedH<Model, Action, HTMLElementTagNameMap['script']>;
    section: NamedH<Model, Action, HTMLElementTagNameMap['section']>;
    select: NamedH<Model, Action, HTMLElementTagNameMap['select']>;
    slot: NamedH<Model, Action, HTMLElementTagNameMap['slot']>;
    small: NamedH<Model, Action, HTMLElementTagNameMap['small']>;
    source: NamedH<Model, Action, HTMLElementTagNameMap['source']>;
    span: NamedH<Model, Action, HTMLElementTagNameMap['span']>;
    strong: NamedH<Model, Action, HTMLElementTagNameMap['strong']>;
    style: NamedH<Model, Action, HTMLElementTagNameMap['style']>;
    sub: NamedH<Model, Action, HTMLElementTagNameMap['sub']>;
    sup: NamedH<Model, Action, HTMLElementTagNameMap['sup']>;
    table: NamedH<Model, Action, HTMLElementTagNameMap['table']>;
    tbody: NamedH<Model, Action, HTMLElementTagNameMap['tbody']>;
    td: NamedH<Model, Action, HTMLElementTagNameMap['td']>;
    template: NamedH<Model, Action, HTMLElementTagNameMap['template']>;
    textarea: NamedH<Model, Action, HTMLElementTagNameMap['textarea']>;
    tfoot: NamedH<Model, Action, HTMLElementTagNameMap['tfoot']>;
    th: NamedH<Model, Action, HTMLElementTagNameMap['th']>;
    thead: NamedH<Model, Action, HTMLElementTagNameMap['thead']>;
    time: NamedH<Model, Action, HTMLElementTagNameMap['time']>;
    title: NamedH<Model, Action, HTMLElementTagNameMap['title']>;
    tr: NamedH<Model, Action, HTMLElementTagNameMap['tr']>;
    track: NamedH<Model, Action, HTMLElementTagNameMap['track']>;
    u: NamedH<Model, Action, HTMLElementTagNameMap['u']>;
    ul: NamedH<Model, Action, HTMLElementTagNameMap['ul']>;
    var: NamedH<Model, Action, HTMLElementTagNameMap['var']>;
    video: NamedH<Model, Action, HTMLElementTagNameMap['video']>;
    wbr: NamedH<Model, Action, HTMLElementTagNameMap['wbr']>;
  }
}

export type NamedH<Model, Action, Elem extends Node> = (...args: Array<Props<Model, Action, Elem>|SDOM<Model, Action>|string|number>) => SDOM<Model, Action, Elem>;

export type NamedH1<Model, Action, Elem = HTMLElement> = {
  (...args: Array<Props<Model, Action, Elem>>): SDOM<Model, Action>;
};

h.a = h.bind(void 0, 'a') as any;
h.abbr = h.bind(void 0, 'abbr') as any;
h.address = h.bind(void 0, 'address') as any;
h.applet = h.bind(void 0, 'applet') as any;
h.area = h.bind(void 0, 'area') as any;
h.article = h.bind(void 0, 'article') as any;
h.aside = h.bind(void 0, 'aside') as any;
h.audio = h.bind(void 0, 'audio') as any;
h.b = h.bind(void 0, 'b') as any;
h.base = h.bind(void 0, 'base') as any;
h.basefont = h.bind(void 0, 'basefont') as any;
h.bdo = h.bind(void 0, 'bdo') as any;
h.blockquote = h.bind(void 0, 'blockquote') as any;
h.body = h.bind(void 0, 'body') as any;
h.br = h.bind(void 0, 'br') as any;
h.button = h.bind(void 0, 'button') as any;
h.canvas = h.bind(void 0, 'canvas') as any;
h.caption = h.bind(void 0, 'caption') as any;
h.cite = h.bind(void 0, 'cite') as any;
h.code = h.bind(void 0, 'code') as any;
h.col = h.bind(void 0, 'col') as any;
h.colgroup = h.bind(void 0, 'colgroup') as any;
h.data = h.bind(void 0, 'data') as any;
h.datalist = h.bind(void 0, 'datalist') as any;
h.dd = h.bind(void 0, 'dd') as any;
h.del = h.bind(void 0, 'del') as any;
h.details = h.bind(void 0, 'details') as any;
h.dfn = h.bind(void 0, 'dfn') as any;
h.dialog = h.bind(void 0, 'dialog') as any;
h.dir = h.bind(void 0, 'dir') as any;
h.div = h.bind(void 0, 'div') as any;
h.dl = h.bind(void 0, 'dl') as any;
h.dt = h.bind(void 0, 'dt') as any;
h.em = h.bind(void 0, 'em') as any;
h.embed = h.bind(void 0, 'embed') as any;
h.fieldset = h.bind(void 0, 'fieldset') as any;
h.figcaption = h.bind(void 0, 'figcaption') as any;
h.figure = h.bind(void 0, 'figure') as any;
h.font = h.bind(void 0, 'font') as any;
h.footer = h.bind(void 0, 'footer') as any;
h.form = h.bind(void 0, 'form') as any;
h.frame = h.bind(void 0, 'frame') as any;
h.frameset = h.bind(void 0, 'frameset') as any;
h.h1 = h.bind(void 0, 'h1') as any;
h.h2 = h.bind(void 0, 'h2') as any;
h.h3 = h.bind(void 0, 'h3') as any;
h.h4 = h.bind(void 0, 'h4') as any;
h.h5 = h.bind(void 0, 'h5') as any;
h.h6 = h.bind(void 0, 'h6') as any;
h.head = h.bind(void 0, 'head') as any;
h.header = h.bind(void 0, 'header') as any;
h.hgroup = h.bind(void 0, 'hgroup') as any;
h.hr = h.bind(void 0, 'hr') as any;
h.html = h.bind(void 0, 'html') as any;
h.i = h.bind(void 0, 'i') as any;
h.iframe = h.bind(void 0, 'iframe') as any;
h.img = h.bind(void 0, 'img') as any;
h.input = h.bind(void 0, 'input') as any;
h.ins = h.bind(void 0, 'ins') as any;
h.kbd = h.bind(void 0, 'kbd') as any;
h.label = h.bind(void 0, 'label') as any;
h.legend = h.bind(void 0, 'legend') as any;
h.li = h.bind(void 0, 'li') as any;
h.link = h.bind(void 0, 'link') as any;
h.main = h.bind(void 0, 'main') as any;
h.map = h.bind(void 0, 'map') as any;
h.mark = h.bind(void 0, 'mark') as any;
h.marquee = h.bind(void 0, 'marquee') as any;
h.menu = h.bind(void 0, 'menu') as any;
h.meta = h.bind(void 0, 'meta') as any;
h.meter = h.bind(void 0, 'meter') as any;
h.nav = h.bind(void 0, 'nav') as any;
h.noscript = h.bind(void 0, 'noscript') as any;
h.object = h.bind(void 0, 'object') as any;
h.ol = h.bind(void 0, 'ol') as any;
h.optgroup = h.bind(void 0, 'optgroup') as any;
h.option = h.bind(void 0, 'option') as any;
h.output = h.bind(void 0, 'output') as any;
h.p = h.bind(void 0, 'p') as any;
h.param = h.bind(void 0, 'param') as any;
h.picture = h.bind(void 0, 'picture') as any;
h.pre = h.bind(void 0, 'pre') as any;
h.progress = h.bind(void 0, 'progress') as any;
h.q = h.bind(void 0, 'q') as any;
h.rt = h.bind(void 0, 'rt') as any;
h.ruby = h.bind(void 0, 'ruby') as any;
h.s = h.bind(void 0, 's') as any;
h.samp = h.bind(void 0, 'samp') as any;
h.script = h.bind(void 0, 'script') as any;
h.section = h.bind(void 0, 'section') as any;
h.select = h.bind(void 0, 'select') as any;
h.slot = h.bind(void 0, 'slot') as any;
h.small = h.bind(void 0, 'small') as any;
h.source = h.bind(void 0, 'source') as any;
h.span = h.bind(void 0, 'span') as any;
h.strong = h.bind(void 0, 'strong') as any;
h.style = h.bind(void 0, 'style') as any;
h.sub = h.bind(void 0, 'sub') as any;
h.sup = h.bind(void 0, 'sup') as any;
h.table = h.bind(void 0, 'table') as any;
h.tbody = h.bind(void 0, 'tbody') as any;
h.td = h.bind(void 0, 'td') as any;
h.template = h.bind(void 0, 'template') as any;
h.textarea = h.bind(void 0, 'textarea') as any;
h.tfoot = h.bind(void 0, 'tfoot') as any;
h.th = h.bind(void 0, 'th') as any;
h.thead = h.bind(void 0, 'thead') as any;
h.time = h.bind(void 0, 'time') as any;
h.title = h.bind(void 0, 'title') as any;
h.tr = h.bind(void 0, 'tr') as any;
h.track = h.bind(void 0, 'track') as any;
h.u = h.bind(void 0, 'u') as any;
h.ul = h.bind(void 0, 'ul') as any;
h.var = h.bind(void 0, 'var') as any;
h.video = h.bind(void 0, 'video') as any;
h.wbr = h.bind(void 0, 'wbr') as any;
